/* Queste sono le righe di codice che ho usato per creare le mie 3 tabelle con i dataset che voi avete consigliato.
   Sono consapevole che i nomi di alcune colonne siano molto lunghi e probabilmente necessitano di essere accorciati,
   il problema è che in parte ritengo giusto lasciarle così essendo alla fine delle nomenclature abbastanza esplicative.
   Voglio dire isomma che non saprei come abbreviarle in maniera corretta al momento.*/

-- Tabella con i dati globali
create table if not exists world_dataset (
	Country_name varchar(50),
	Density int,
	Abbreviation varchar(50),
	Agricultural_land varchar(50),
	Land_area int,
	Armed_forces_size int,
	Birth_rate decimal,
	Calling_code int,
	Capital varchar(50),
	Co2_emissions_T int,
	CPI decimal,
	CPI_change varchar(50),
	Currency_code varchar(50),
	Fertility_rate_avg decimal,
	Forested_area varchar(50),
	Gasoline_price_$ decimal,
	GDP_$ bigint,
	Gross_primary_education_enrl varchar(50),
	Gross_tertiary_education_enrl varchar(50),
	Infant_mortality_1000 decimal,
	Largest_city varchar(50),
	Life_expectancy decimal,
	Maternal_mortality_ratio_100000 int,
	Minimum_wage_$ decimal,
	Official_language varchar(50),
	OOP_healt_expenditure varchar(50),
	Physicians_per_thousent decimal,
	Population int,
	Labor_force_participation varchar(50),
	Tax_revenue varchar(50),
	Total_tax_rate varchar(50),
	Unemployment_rate varchar(50),
	Urban_population int
);

-- Tabella con i dati riguardanti i migranti dispersi
create table if not exists world_missing_migrants_dataset (
	incident_type varchar(255),
	incident_year int,
	reported_month varchar(255),
	region_of_origin varchar(255),
	region_of_incident varchar(255),
	country_of_origin varchar(255),
	number_of_dead int,
	min_estimate_num_of_missing int,
	total_num_of_dead_and_missingint int,
	num_of_survivors int,
	number_of_females int,
	number_of_males int,
	number_of_children int,
	cause_of_death varchar(255),
	migration_route varchar(255),
	location_of_death varchar(500),
	information_source varchar(255),
	cordinates varchar(255),
	UNSD_geographical_grouping varchar(255)
);


-- Tabella con i dati riguardanti l'energia sostenibile
create table if not exists global_data_sustainable_energy (
	Entity varchar(50), 
	Year int, 
	Access_to_electricity_percentage_of_population decimal, 
	Access_to_clean_fuels_for_cooking decimal, 
	Renewable_electricity_generating_capacity_per_capita decimal, 
	Financial_flows_to_developing_countries_US_$ decimal, 
	Renewable_energy_share_in_the_total_final_energy_consumption_percentage decimal, 
	Electricity_from_fossil_fuels_TWh decimal, 
	Electricity_from_nuclear_TWh decimal, 
	Electricity_from_renewables_TWh decimal, 
	Low_carbon_electricity_percentage_electricity decimal, 
	Primary_energy_consumption_per_capita_kWh_person decimal, 
	Energy_intensity_level_of_primary_energy_MJ_$2017_PPP_GDP decimal, 
	Value_co2_emissions_kt_by_country decimal, 
	Renewables_percentage_equivalent_primary_energy decimal, 
	gdp_growth decimal, 
	gdp_per_capita decimal, 
	Density_P_Km2 decimal, 
	Land_Area_Km2 decimal, 
	Latitude decimal, 
	Longitude decimal
);

-- Tabella contenente paesi ad alto ISU (per le ultime query)
create table if not exists high_ISU(
	country varchar(50));
	
insert into high_ISU (country)
values
('Switzerland'),
('Norway'),
('Iceland'),
('Hong Kong'),
('Australia'),
('Denmark'),
('Sweden'),
('Ireland'),
('Germany'),
('Netherlands'),
('Finland'),
('Singapore'),
('Belgium'),
('New Zealand'),
('Canada'),
('Liechtenstein'),
('Luxembourg'),
('United Kingdom'),
('Japan'),
('South Korea'),
('United States'),
('Israel'),
('Malta'),
('Slovenia'),
('Austria'),
('United Arab Emirates'),
('Spain'),
('France'),
('Cyprus'),
('Italy'),
('Estonia'),
('Czech Republic'),
('Greece'),
('Poland'),
('Bahrain'),
('Lithuania'),
('Saudi Arabia'),
('Portugal'),
('Latvia'),
('Andorra'),
('Croatia'),
('Chile'),
('Qatar'),
('San Marino'),
('Slovakia'),
('Hungary'),
('Argentina'),
('Turkey'),
('Montenegro'),
('Kuwait'),
('Brunei'),
('Russia'),
('Romania'),
('Oman'),
('Bahamas'),
('Kazakhstan'),
('Trinidad and Tobago'),
('Costa Rica'),
('Uruguay'),
('Belarus'),
('Panama'),
('Malaysia'),
('Georgia'),
('Mauritius'),
('Serbia'),
('Thailand');